import type { Book, Review, BlogPost } from '@/types'

export const MOCK_BOOKS: Book[] = [
  {
    id: 'mock-1',
    title: 'Weep Not, Child',
    author: 'Ngũgĩ wa Thiong\'o',
    description: 'The first major novel in English by an East African author. Set during the Mau Mau uprising in Kenya, it tells the story of Njoroge, a young boy who pins his hopes on education while his family is drawn into the conflict.',
    category: 'Fiction',
    price_hard: 850,
    price_ebook: 450,
    cover_url: null,
    cover_public_id: null,
    is_deal: false,
    is_featured: true,
    is_top_seller: true,
    in_stock: true,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'mock-2',
    title: 'The River and the Source',
    author: 'Margaret A. Ogola',
    description: 'A sweeping family saga spanning four generations of Kenyan women. Beginning in pre-colonial Luoland, the novel follows the descendants of Akoko as Kenya transforms around them.',
    category: 'Fiction',
    price_hard: 950,
    price_ebook: 500,
    cover_url: null,
    cover_public_id: null,
    is_deal: false,
    is_featured: true,
    is_top_seller: true,
    in_stock: true,
    created_at: '2026-01-02T00:00:00Z',
  },
  {
    id: 'mock-3',
    title: 'The River Between',
    author: 'Ngũgĩ wa Thiong\'o',
    description: 'Two Gikuyu villages divided by a river and by Christianity face each other across a valley. A young man tries to bridge the divide in a story of love, tradition and the wounds of colonialism.',
    category: 'Fiction',
    price_hard: 800,
    price_ebook: null,
    cover_url: null,
    cover_public_id: null,
    is_deal: false,
    is_featured: false,
    is_top_seller: false,
    in_stock: true,
    created_at: '2026-01-03T00:00:00Z',
  },
  {
    id: 'mock-4',
    title: 'Atomic Habits',
    author: 'James Clear',
    description: 'An easy and proven way to build good habits and break bad ones. Tiny changes, remarkable results — the most comprehensive guide on how habits work and how to change them.',
    category: 'Self-Help',
    price_hard: 1100,
    price_ebook: 600,
    cover_url: null,
    cover_public_id: null,
    is_deal: true,
    is_featured: false,
    is_top_seller: true,
    in_stock: true,
    created_at: '2026-01-04T00:00:00Z',
  },
  {
    id: 'mock-5',
    title: 'The Lean Startup',
    author: 'Eric Ries',
    description: 'How constant innovation creates radically successful businesses. Learn how to drive a startup — how to steer, when to turn, and when to persevere.',
    category: 'Business',
    price_hard: 1200,
    price_ebook: 650,
    cover_url: null,
    cover_public_id: null,
    is_deal: false,
    is_featured: true,
    is_top_seller: true,
    in_stock: true,
    created_at: '2026-01-05T00:00:00Z',
  },
  {
    id: 'mock-6',
    title: 'Zero to One',
    author: 'Peter Thiel',
    description: 'Notes on startups, or how to build the future. Every moment in business happens only once. What valuable company is nobody building?',
    category: 'Business',
    price_hard: 1150,
    price_ebook: 620,
    cover_url: null,
    cover_public_id: null,
    is_deal: false,
    is_featured: false,
    is_top_seller: false,
    in_stock: true,
    created_at: '2026-01-06T00:00:00Z',
  },
  {
    id: 'mock-7',
    title: 'Think and Grow Rich',
    author: 'Napoleon Hill',
    description: 'The landmark bestseller revised for the 21st century. Based on research into the habits and mindsets of the most successful people of the era.',
    category: 'Self-Help',
    price_hard: 900,
    price_ebook: 480,
    cover_url: null,
    cover_public_id: null,
    is_deal: false,
    is_featured: false,
    is_top_seller: false,
    in_stock: true,
    created_at: '2026-01-07T00:00:00Z',
  },
  {
    id: 'mock-8',
    title: 'Ikigai: The Japanese Secret to a Long and Happy Life',
    author: 'Héctor García',
    description: 'What\'s your reason for being? The people of Japan\'s Okinawa island believe ikigai is the reason we get up in the morning.',
    category: 'Self-Help',
    price_hard: 1050,
    price_ebook: 550,
    cover_url: null,
    cover_public_id: null,
    is_deal: false,
    is_featured: false,
    is_top_seller: false,
    in_stock: true,
    created_at: '2026-01-08T00:00:00Z',
  },
]

export const MOCK_REVIEWS: (Review & { books?: { id: string; title: string } })[] = [
  {
    id: 'rev-1',
    book_id: 'mock-1',
    reviewer: 'Amina Wanjiku',
    body: 'This book changed how I see Kenya\'s history. Ngũgĩ writes with such pain and tenderness. I cried on the matatu home.',
    rating: 5,
    approved: true,
    created_at: '2026-02-10T10:00:00Z',
    books: { id: 'mock-1', title: 'Weep Not, Child' },
  },
  {
    id: 'rev-2',
    book_id: 'mock-4',
    reviewer: 'David Otieno',
    body: 'Atomic Habits is the most practical book I have ever read. I have already recommended it to everyone at my office. Delivery was super fast!',
    rating: 5,
    approved: true,
    created_at: '2026-02-15T14:00:00Z',
    books: { id: 'mock-4', title: 'Atomic Habits' },
  },
  {
    id: 'rev-3',
    book_id: 'mock-2',
    reviewer: 'Fatuma Hassan',
    body: 'The River and the Source is a masterpiece. Ogola captures Kenyan women\'s strength across generations. Buy this for your mother, your sister, your daughter.',
    rating: 5,
    approved: true,
    created_at: '2026-03-01T09:00:00Z',
    books: { id: 'mock-2', title: 'The River and the Source' },
  },
]

export const MOCK_BLOG_POSTS: BlogPost[] = [
  {
    id: 'post-1',
    title: '5 Kenyan Books Every Reader Should Own',
    slug: '5-kenyan-books-every-reader-should-own',
    excerpt: 'From Ngũgĩ to Ogola — a curated list of essential titles from Kenya\'s greatest storytellers.',
    body: 'Kenya has produced some of Africa\'s most powerful voices in literature. Whether you are a lifelong bookworm or just beginning your reading journey, these five titles belong on your shelf.\n\n1. Weep Not, Child — Ngũgĩ wa Thiong\'o\nThe novel that put East African fiction on the world map. Essential reading.\n\n2. The River and the Source — Margaret Ogola\nA multigenerational saga that will make you laugh, cry and feel proud.\n\n3. A Grain of Wheat — Ngũgĩ wa Thiong\'o\nA complex portrait of the struggle for independence.\n\n4. Dust — Yvonne Adhiambo Owuor\nA stunning debut novel about grief, identity and the violence that shapes a nation.\n\n5. Petals of Blood — Ngũgĩ wa Thiong\'o\nA searing indictment of post-independence Kenya. Bold, angry and brilliant.',
    cover_url: null,
    published: true,
    created_at: '2026-04-01T00:00:00Z',
  },
  {
    id: 'post-2',
    title: 'Why Ebooks Are Perfect for the Nairobi Commute',
    slug: 'ebooks-perfect-for-nairobi-commute',
    excerpt: 'Matatu rides, traffic jams and lunch breaks are better with a book in your pocket.',
    body: 'Anyone who has spent an hour in Nairobi traffic knows the feeling: you\'re stuck, you\'re frustrated, and your phone is the only thing standing between you and boredom.\n\nHere\'s our case for ebooks:\n\nInstant delivery — order and receive it on WhatsApp within minutes.\nZero weight — a phone weighs nothing.\nPrivacy — nobody on the matatu needs to know you\'re reading self-help.\nNight reading — backlit screen, dark mode, 11pm on your bed. Perfect.',
    cover_url: null,
    published: true,
    created_at: '2026-04-10T00:00:00Z',
  },
  {
    id: 'post-3',
    title: 'How to Build a Reading Habit That Actually Sticks',
    slug: 'build-reading-habit-that-sticks',
    excerpt: 'Practical advice for readers in Nairobi who want to read more but keep getting distracted.',
    body: 'Reading more is one of those goals that sounds easy until life happens. Here is what actually works.\n\nStart with 10 pages a day. Not a chapter. Not 30 minutes. Ten pages.\n\nKeep a book in your bag always. The bus, the queue at the supermarket, waiting for the doctor — these moments add up.\n\nFinish what you start, mostly. Give a book 50 pages. If it still hasn\'t grabbed you, put it down.\n\nRead what you actually like. Not what you think you should read.',
    cover_url: null,
    published: true,
    created_at: '2026-04-20T00:00:00Z',
  },
]
